[window]
startup_mode = "Maximized"
padding.x = 4
padding.y = 4
decorations = "Buttonless"

[font]
size = 16
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
