#!/bin/zsh

if [ -t 1 ]; then
    selected=$(find ~/dotfiles ~/Documents -type d | fzf)
    if [[ -z $selected ]]; then
        return 0
    fi

    selected_name=$(basename "$selected" | tr -cs '[:alnum:]' '_')
    tmux_running=$(pgrep tmux)

    if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
        tmux new-session -s "$selected_name" -c "$selected"
        return 0
    fi

    if ! tmux has-session -t="$selected_name" 2>/dev/null; then
        tmux new-session -ds "$selected_name" -c "$selected"
    fi

    if [[ -z $TMUX ]]; then
        tmux attach-session -t "$selected_name"
    else
        tmux switch-client -t "$selected_name"
    fi
else
    echo "Not running in a terminal. Please run in a terminal environment."
    return 1
fi
