#!/bin/zsh

if [ -t 1 ]; then
    selected=$(find ~/dotfiles/ ~/Documents/ ~/Documents/ -type d | fzf)
    if [[ -z $selected ]]; then
        return 0
    fi

    selected_name=$(basename "$selected" | tr . _)
    tmux_running=$(pgrep tmux)

    if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
        tmux new-session -s $selected_name -c "$selected"
        return 0
    fi

    if ! tmux has-session -t=$selected_name 2>/dev/null; then
        tmux new-session -ds $selected_name -c "$selected"
    fi

    tmux switch-client -t $selected_name
else
    echo "Not running in a terminal. Please run in a terminal environment."
    return 1
fi
